Lecture 4 problems
M-Ahmed-Khan/programming-fundamentals pull request #2
Opened 2023-08-12 13:33 UTC by M-Ahmed-Khan

2023-08-16 10:23 UTC, nf-khan requested changes
Add description to PR.

2023-08-16 10:23 UTC, nf-khan commented on problem-04.c
> +        printf("\n%d x %d = %d", number, i, number * i);
`\n` should be placed after the expression

2023-08-16 10:23 UTC, nf-khan commented on problem-05.c
> +        (i < 1) ? printf("%d", number) : printf("\n%d", number);
1. Why are you adding conditional statement here? It can be done simply without any conditional. 
2. `\n` should be placed after the expression
3. What will the output if number is `0`, also handle this case.

2023-08-16 10:23 UTC, nf-khan commented on problem-07.c
> +
remove blank space

2023-08-16 10:23 UTC, nf-khan commented on problem-06.c
> +    for (int i = 1; i <= number_2; i++)
What will the output if number is `0`, also handle this case.

2023-08-16 10:23 UTC, nf-khan commented on problem-07.c
Did you have run this code? This code has error.

2023-08-17 10:18 UTC, M-Ahmed-Khan commented on problem-04.c
> +        printf("\n%d x %d = %d", number, i, number * i);
Updated according to your comment

2023-08-17 10:20 UTC, M-Ahmed-Khan commented on problem-05.c
> +        (i < 1) ? printf("%d", number) : printf("\n%d", number);
1. I did it for formatting purposes but removed it now
2. Placed it after the expression
3. This case is already handled. If number is `0` the loop condition will be `false` and the program will return

2023-08-17 10:21 UTC, M-Ahmed-Khan commented on problem-07.c
> +
Removed

2023-08-17 10:22 UTC, M-Ahmed-Khan commented on problem-06.c
> +    for (int i = 1; i <= number_2; i++)
Handled the `0` case as well

2023-08-17 10:23 UTC, M-Ahmed-Khan commented on problem-07.c
I have fixed the error. It is running perfectly

2023-08-24 05:20 UTC, nf-khan approved these changes
PR approved but also implement the changes first

2023-08-24 05:20 UTC, nf-khan commented on problem-08.c
> +    for (number; number != 0; number /= 10)
On my side I am getting this `warning: expression result unused [-Wunused-value]` and it can be resolved as `for (; number != 0; number /= 10)`

2023-08-26 09:33 UTC, closed without merging